const svg = d3.select('svg')
console.log(svg)
d3.json('data.json').then(data => {
    const rects = svg.selectAll('rect')
                     .data(data)
                     .attr('width', d => d.width)
                     .attr('height', d => d.height)
                     .attr('fill', d => d.fill)
    console.log(rects)
        rects.enter()
        .append('circle')
        .attr('cx', d => d.cx)
        .attr('cy', d => d.cy)
        .attr('r', d => d.r)
        .attr('stroke', d => d.stroke)
        .attr('fill', d => d.fill)
    console.log(rects)

} )
